<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    use HasFactory;

    protected $table = 'animals';
    protected $fillable = [
        'id',
        'type',
        'game_id',
        'x',
        'y'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
